<a href="https://colab.research.google.com/github/xdavi3/Introdu-o-Programa-o-de-Computadores/blob/main/C%C3%B3pia_de_Detectron2_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Atividade 7.1 - Exercício de Fixação**




**Questão 1**

In [ ]:
Considere as linhas de código Python a seguir:

In [ ]:
import numpy as np
dado = [ [1,2,3] , [4,5,6] ]
array = np.array (dado)
print(array.shape)

(2, 3)


O código transforma a lista de listas DADO em um array e exibe o SHAPE do array. Marque a alternativa que representa corretamente a saída do código acima.

Escolha uma opção:

a.
(3, 2)


b.
(2, 3)


c.
2


d.
(2, 3, 2)

**Questão 2**

O código Python a seguir mostra um caso de análise de dimensão matricial:

In [ ]:
import numpy as np
dado = [ [1,2,3,] , [4,5,6]]

array = np.array(dado)
print(array.ndim)

2


Lembrando que NDIM mostra a dimensão da matriz em análise, marque a alternativa correta a seguir sobre a saída do código acima.

Escolha uma opção:

a.
(3, 2)


b.
3


c.
(2, 3)


d.
2


e.
6

**Questão 3**

Considere o código Python a seguir para responder à questão:

In [ ]:
import numpy as np
arr1 = np.zeros ((2,2,2,2))
arr2 = arr1+2
arr3 = arr2*arr2
print(np.sum(arr3))

64.0


A função SUM retorna a soma de todos os elementos da matriz passada como parâmetro. Marque a alternativa que representa a saída do código.

Escolha uma opção:

a.
2.0


b.
15.0

4.0




c.
64.0


d.
32.0


e.
0.0

**Questão 4**


Vamos considerar a estrutura de dados Pyhton a seguir:

In [ ]:
import numpy as np
arr = np.array ([-0.5,12.9,10.1,-3.7,1.])
print(arr.astype(np.int32))

[ 0 12 10 -3  1]


No código, há uma mudança no tipo de dados do array. Marque a alternativa que representa melhor a saída do código.

Escolha uma opção:

a.
[ 0 12 10  3  1]


b.
[ -0 13 10 -4  1]


c.
[ 0 12 10 -3  1]


d.
[ 0 13 10 -4  1]


e.
[ -1 13 10 -4  1]

**Questão 5**

 código Python a seguir é formado de arrays e slices de arrays.

In [ ]:
import numpy as np
arr1 = np.arange (5)
arr2 = arr1[1:4]
arr2 [:] = 15
print (arr1)

[ 0 15 15 15  4]


Preste atenção nas modificações dos arrays e marque a opção a seguir que representa melhor a saída do código.



Escolha uma opção:

a.
[ 0 1 2 3 4]


b.
[ 15 15 15 ]


c.
[ 1 15 15 15 5]


d.
Erro


e.
[ 0 15 15 15  4]